version: '3.3'

services:
    dto2databundle_php:
        image: dh.rinsvent.ru/php8dev
        container_name: dto2databundle_php
        volumes:
            - ./:/app
        environment:
            USE_COMPOSER_SCRIPTS: 0
            PHP_IDE_CONFIG: "serverName=dto2databundle_php"

networks:
    default:
        external:
            name: full-project
